package com.yichao.evilgodxu.data.music.analysis

import android.content.Context
import androidx.core.net.toUri
import com.yichao.evilgodxu.data.music.model.MusicTrack
import java.io.File
import java.io.FileInputStream
import java.io.InputStream

// AI 生成器的「署名」取证：从容器元数据中找出生成链自动写入的标识，
// 命中即视为生成器自报出身，无需再做频谱分析。
//
// 取证依据来自各家生成器的公开导出行为：
//   Suno：ID3 TENC（编码器）/ COMM（含 clip id 与创作时间）、M4A udta 盒子、
//         以及 C2PA 内容凭证（断言 com.suno.provenance、trainedAlgorithmicMedia）；
//   Udio：M4A udta 盒子，可选 Google SynthID；
//   ElevenLabs 等语音合成：编码器字段写模型名 + C2PA。
// 这些字段由生成链路自动注入，不随用户重命名标题而改变；
// 但导出后经转码或重封装会被剥离，故本探针只能覆盖「未清洗」的样本。
//
// 匹配分三级，从严到宽，避免把普通曲目误判：
//   A 级 内容凭证标记：C2PA/JUMBF 结构标识，只会由合规生成链路写入，直接采信；
//   B 级 显式生成声明：`made with suno` 一类明确短语，出现在任何文本字段都采信；
//   C 级 生成器署名：产品名出现在「产出软件」类字段（编码器/软件/工具）中才采信；
//        标题/艺术家/歌词等用户可编辑字段中出现的同名不作数，避免同名艺人误伤。
internal object AiSourceTagProbe {

    // 头部扫描窗口：ID3v2/Vorbis comment 位于文件头；未被 faststart 优化的 MP4 把 moov 放在文件尾，
    // 故尾部另开窗口。WAV 的 RIFF 元数据块（LIST/INFO、承载 ID3v2 的 "ID3 " 块）常落在 data 之后、
    // 远超出这两个窗口，改由块表定位后按绝对偏移定点读取
    private const val HEAD_SCAN_BYTES = 128 * 1024
    private const val TAIL_SCAN_BYTES = 128 * 1024

    // 单次注释条目上限：防御性截断，避免畸形长度字段触发超大分配
    private const val MAX_COMMENT_ENTRIES = 4096

    // RIFF 块结构与遍历上限：容器头 12 字节（"RIFF" + 尺寸 + "WAVE"），块头 8 字节（标识 + 小端长度）；
    // 块体读取上限防御畸形长度字段触发超大分配，遍历上限防御长度字段导致的长循环
    private const val RIFF_HEADER_BYTES = 12
    private const val RIFF_CHUNK_HEADER_BYTES = 8
    private const val MAX_RIFF_CHUNK_BYTES = 4 * 1024 * 1024
    private const val MAX_RIFF_CHUNKS = 4096

    // A 级：内容凭证结构标记（大小写不敏感，直接对扫描窗口做原始字节匹配）
    private val PROVENANCE_MARKERS = listOf(
        "c2pa", "jumbf", "trainedalgorithmicmedia",
        "com.suno.provenance", "synthid", "contentcredentials",
    )

    // B 级：明确的生成声明短语
    private val EXPLICIT_PHRASES = listOf(
        "made with suno", "made with udio", "suno ai", "udio ai",
        "ai generated", "ai-generated", "generated by ai", "generated with ai",
        "suno.com", "udio.com", "musicgen", "audiocraft", "stable audio",
        "ai 生成", "ai生成", "人工智能生成", "ai合成", "ai 合成",
    )

    // C 级：生成器产品名，仅在「产出软件」类字段中出现时采信
    private val SOFTWARE_HINTS = listOf(
        "suno", "udio", "riffusion", "mubert", "boomy", "aiva", "soundraw",
        "beatoven", "loudly", "elevenlabs", "ace-step", "acestep",
        "diffrhythm", "mureka", "lalal", "soundful", "海绵音乐", "天工",
        "网易天音", "tianyin",
    )

    // 「产出软件」类字段：编码器、软件、工具署名。键统一转大写后比对
    private val SOFTWARE_FIELDS = setOf(
        "TENC", "TSSE", "TOOL", "ENCODER", "ENCODED-BY", "SOFTWARE",
        "CTOO", "CSWR", "ISFT", "ISRF", "APPLICATION", "WRITING APP", "VENDOR",
    )

    // 取证结论：命中的签名与其来源字段，供日志与诊断
    internal data class TagEvidence(val signature: String, val field: String)

    // 判定入口：返回 null 表示未发现生成器署名；非本地文件一律不适用
    fun probe(context: Context, track: MusicTrack): TagEvidence? = runCatching {
        val length = fileLength(context, track)
        val head = readHead(context, track)
        if (head.isEmpty()) return@runCatching null
        // 头窗未覆盖整个元数据区（即文件更大）时再取尾窗，覆盖 moov 后置的 MP4
        val tail = if (head.size >= HEAD_SCAN_BYTES && head.size < length) readTail(context, track) else null
        probeBytes(head, tail, length) { offset, count -> readRange(context, track, offset, count) }
    }.getOrNull()

    // 判定入口的纯字节部分：head 为文件头窗口，tail 为文件尾窗口（可为 null），fileLength 为文件总长；
    // readAt 供窗口之外按绝对偏移定点读取，为 null 时只认窗口内的元数据
    internal fun probeBytes(
        head: ByteArray,
        tail: ByteArray?,
        fileLength: Long,
        readAt: ((Long, Int) -> ByteArray?)? = null,
    ): TagEvidence? {
        val fields = LinkedHashMap<String, String>()
        // WAV 的标签块可能远在扫描窗口之外：先按块表定位取回，再连同窗口一起做原始标记匹配
        val riffTags =
            if (head.startsWithAscii("RIFF")) extractRiffFields(head, fileLength, readAt, fields) else emptyList()
        matchProvenance(head, tail, riffTags)?.let { return it }
        extractFields(head, fields)
        if (tail != null) extractFields(tail, fields)
        return matchText(fields)
    }

    // ---- 容器字段抽取 ----

    // 按窗口首字节判定容器并抽取字段；RIFF 需按块表定位，由 extractRiffFields 单独处理
    private fun extractFields(bytes: ByteArray, out: MutableMap<String, String>) {
        when {
            bytes.startsWithAscii("ID3") -> parseId3v2(bytes, out)
            bytes.startsWithAscii("fLaC") -> parseFlacBlocks(bytes, out)
            bytes.startsWithAscii("OggS") -> parseOggVorbis(bytes, out)
            isMp4Like(bytes) -> parseMp4UserData(bytes, out)
        }
    }

    // WAV：按块表遍历 LIST/INFO 与承载 ID3v2 的 "ID3 " 块。块头落在头窗内就地取，
    // 落在窗口外（data 之后）按绝对偏移定点读取，故 data 块再大也不影响定位；
    // 返回读到的 ID3 块内容，供 C2PA 之类的原始标记匹配
    private fun extractRiffFields(
        head: ByteArray,
        fileLength: Long,
        readAt: ((Long, Int) -> ByteArray?)?,
        out: MutableMap<String, String>,
    ): List<ByteArray> {
        val tags = mutableListOf<ByteArray>()
        val end = if (fileLength > 0) fileLength else head.size.toLong()
        var p = RIFF_HEADER_BYTES.toLong()
        repeat(MAX_RIFF_CHUNKS) {
            val header = windowAt(head, p, RIFF_CHUNK_HEADER_BYTES, readAt) ?: return tags
            val size = leInt(header, 4)
            if (size < 0 || p + RIFF_CHUNK_HEADER_BYTES + size > end) return tags
            val bodyStart = p + RIFF_CHUNK_HEADER_BYTES
            when (String(header, 0, 4, Charsets.ISO_8859_1)) {
                "LIST" -> windowAt(head, bodyStart, minOf(size, MAX_RIFF_CHUNK_BYTES), readAt)
                    ?.takeIf { it.size >= 4 && String(it, 0, 4, Charsets.ISO_8859_1) == "INFO" }
                    ?.let { parseRiffInfoItems(it, out) }
                "id3 ", "ID3 " -> windowAt(head, bodyStart, minOf(size, MAX_RIFF_CHUNK_BYTES), readAt)?.let {
                    parseId3v2(it, out)
                    tags += it
                }
            }
            p = bodyStart + size + (size and 1)
        }
        return tags
    }

    // 取文件 [offset, offset + count) 的字节：优先头窗，未覆盖该区间时定点读取；
    // 读不满 count 字节即视为不可用，避免按半截块头解析
    private fun windowAt(
        head: ByteArray,
        offset: Long,
        count: Int,
        readAt: ((Long, Int) -> ByteArray?)?,
    ): ByteArray? {
        if (offset < 0 || count <= 0) return null
        if (offset + count <= head.size) return head.copyOfRange(offset.toInt(), offset.toInt() + count)
        return readAt?.invoke(offset, count)?.takeIf { it.size >= count }
    }

    // ID3v2：逐帧取文本。文本帧为定长块，未同步化只影响字节填充，不改变可读性，
    // 故不做去同步化处理
    private fun parseId3v2(bytes: ByteArray, out: MutableMap<String, String>) {
        if (bytes.size < 10) return
        val major = bytes[3].toInt() and 0xFF
        val end = minOf(10 + syncSafe(bytes, 6), bytes.size)
        var p = 10
        while (p + 10 <= end) {
            val id = String(bytes, p, 4, Charsets.ISO_8859_1)
            if (id[0] == '\u0000') break
            val size = if (major >= 4) syncSafe(bytes, p + 4) else beInt(bytes, p + 4)
            if (size <= 0 || p + 10 + size > end) break
            val body = bytes.copyOfRange(p + 10, p + 10 + size)
            when {
                id == "TXXX" || id == "WXXX" -> splitDescription(body)?.let { (desc, value) ->
                    putText(out, id, "$desc=$value")
                }
                id == "COMM" || id == "USLT" -> commentText(body)?.let { putText(out, id, it) }
                id[0] == 'T' && id[1] != '\u0000' -> putText(out, id, id3Text(body))
                id[0] == 'W' -> putText(out, id, plainText(body))
            }
            p += 10 + size
        }
    }

    // FLAC：遍历 metadata block，取 VORBIS_COMMENT（类型 4）与 APPLICATION（类型 2）
    private fun parseFlacBlocks(bytes: ByteArray, out: MutableMap<String, String>) {
        var p = 4
        while (p + 4 <= bytes.size) {
            val header = bytes[p].toInt() and 0xFF
            val last = header and 0x80 != 0
            val type = header and 0x7F
            val size = beInt24(bytes, p + 1)
            val from = p + 4
            val to = minOf(from + size, bytes.size)
            if (from >= to) break
            when (type) {
                4 -> parseVorbisComment(bytes, from, to, out)
                2 -> String(bytes, from, minOf(4, to - from), Charsets.ISO_8859_1)
                    .takeIf { it.isNotBlank() }?.let { putText(out, "APPLICATION", it) }
            }
            if (last) break
            p = from + size
        }
    }

    // Ogg/Vorbis：定位 comment header（包类型 3 + vorbis 标识），其后紧跟 vendor 与注释列表
    private fun parseOggVorbis(bytes: ByteArray, out: MutableMap<String, String>) {
        val marker = byteArrayOf(0x03) + "vorbis".toByteArray(Charsets.ISO_8859_1)
        val at = indexOf(bytes, marker) ?: return
        parseVorbisComment(bytes, at + marker.size, bytes.size, out)
    }

    // Vorbis comment 体：小端 vendor 长度 + vendor + 小端条目数 + 逐条 小端长度 + "KEY=value"
    private fun parseVorbisComment(bytes: ByteArray, from: Int, to: Int, out: MutableMap<String, String>) {
        var p = from
        if (p + 4 > to) return
        val vendorLen = leInt(bytes, p)
        p += 4
        if (vendorLen < 0 || p + vendorLen > to) return
        putText(out, "VENDOR", String(bytes, p, vendorLen, Charsets.UTF_8))
        p += vendorLen
        if (p + 4 > to) return
        val count = leInt(bytes, p)
        p += 4
        if (count < 0 || count > MAX_COMMENT_ENTRIES) return
        repeat(count) {
            if (p + 4 > to) return
            val len = leInt(bytes, p)
            p += 4
            if (len < 0 || p + len > to) return
            val entry = String(bytes, p, len, Charsets.UTF_8)
            p += len
            val eq = entry.indexOf('=')
            if (eq > 0) putText(out, entry.substring(0, eq), entry.substring(eq + 1))
        }
    }

    // WAV：LIST 块内 INFO 子块（ISFT/ICMT 等）：载荷自 "INFO" 之后的第一个子块起
    private fun parseRiffInfoItems(info: ByteArray, out: MutableMap<String, String>) {
        var p = 4
        while (p + 8 <= info.size) {
            val id = String(info, p, 4, Charsets.ISO_8859_1)
            val size = leInt(info, p + 4)
            if (size < 0 || p + 8 + size > info.size) break
            putText(out, id, plainText(info.copyOfRange(p + 8, p + 8 + size)))
            p += 8 + size + (size and 1)
        }
    }

    // MP4/M4A：递归下钻 moov→udta→meta→ilst，取条目原子（ctoo/ccmt/cnam 等）的 data 载荷
    private fun parseMp4UserData(bytes: ByteArray, out: MutableMap<String, String>) {
        walkBoxes(bytes, 0, bytes.size, out, 0)
    }

    private fun walkBoxes(bytes: ByteArray, from: Int, to: Int, out: MutableMap<String, String>, depth: Int) {
        if (depth > 6) return
        var p = from
        while (p + 8 <= to) {
            val size = beInt(bytes, p)
            val type = String(bytes, p + 4, 4, Charsets.ISO_8859_1)
            val headerLen = if (size == 1) 16 else 8
            val boxEnd = if (size <= 0) to else minOf(p + size, to)
            if (boxEnd <= p + headerLen) break
            when (type) {
                // 容器原子继续下钻；meta 盒子前置 4 字节版本标志
                "moov", "udta", "trak", "mdia", "minf", "stbl" ->
                    walkBoxes(bytes, p + headerLen, boxEnd, out, depth + 1)
                "meta" -> walkBoxes(bytes, p + headerLen + 4, boxEnd, out, depth + 1)
                "ilst" -> parseIlst(bytes, p + headerLen, boxEnd, out)
            }
            p = boxEnd
        }
    }

    private fun parseIlst(bytes: ByteArray, from: Int, to: Int, out: MutableMap<String, String>) {
        var p = from
        while (p + 8 <= to) {
            val size = beInt(bytes, p)
            val name = normalizeMp4Key(String(bytes, p + 4, 4, Charsets.ISO_8859_1))
            val boxEnd = if (size <= 0) to else minOf(p + size, to)
            if (boxEnd <= p + 8) break
            var q = p + 8
            while (q + 8 <= boxEnd) {
                val childSize = beInt(bytes, q)
                val childType = String(bytes, q + 4, 4, Charsets.ISO_8859_1)
                val childEnd = if (childSize <= 0) boxEnd else minOf(q + childSize, boxEnd)
                if (childEnd <= q + 8) break
                // data 原子：8 字节头 + 8 字节类型/区域标志，其后为载荷
                if (childType == "data" && childEnd - (q + 16) > 0) {
                    putText(out, name, plainText(bytes.copyOfRange(q + 16, childEnd)))
                }
                q = childEnd
            }
            p = boxEnd
        }
    }

    // ---- 匹配 ----

    private fun matchProvenance(head: ByteArray, tail: ByteArray?, extra: List<ByteArray>): TagEvidence? {
        for (marker in PROVENANCE_MARKERS) {
            if (containsAscii(head, marker)) return TagEvidence(marker, "C2PA")
            if (tail != null && containsAscii(tail, marker)) return TagEvidence(marker, "C2PA")
            // 窗口之外取回的标签块同样参与匹配，避免后置元数据里的内容凭证被漏掉
            if (extra.any { containsAscii(it, marker) }) return TagEvidence(marker, "C2PA")
        }
        return null
    }

    private fun matchText(fields: Map<String, String>): TagEvidence? {
        // B 级：显式声明在任何文本字段出现都采信
        val joined = fields.values.joinToString("\u0000").lowercase()
        EXPLICIT_PHRASES.firstOrNull { joined.contains(it) }?.let { return TagEvidence(it, "文本声明") }
        // C 级：产品名须落在产出软件类字段，避免同名艺人/标题误伤
        for ((key, value) in fields) {
            val upper = key.uppercase()
            val field = if (upper in SOFTWARE_FIELDS) upper else if (upper.startsWith("TXXX")) "TXXX" else continue
            val lower = value.lowercase()
            SOFTWARE_HINTS.firstOrNull { lower.contains(it) }?.let { return TagEvidence(it, field) }
        }
        return null
    }

    // ---- 字节与编码工具 ----

    private fun putText(out: MutableMap<String, String>, key: String, value: String) {
        val k = key.trim().trimStart('\uFEFF').ifBlank { return }
        val v = value.replace('\u0000', ' ').trim()
        if (v.isEmpty()) return
        // 同键多条时拼接，便于一次性匹配
        out[k] = out[k]?.let { "$it $v" } ?: v
    }

    private fun openInput(context: Context, track: MusicTrack): InputStream? = when {
        track.path.isNotBlank() -> runCatching { FileInputStream(track.path) }.getOrNull()
        track.audioUri.startsWith("content:") || track.audioUri.startsWith("file:") ->
            runCatching {
                context.contentResolver.openInputStream(track.audioUri.toUri())
            }.getOrNull()
        else -> null
    }

    private fun fileLength(context: Context, track: MusicTrack): Long =
        if (track.path.isNotBlank()) {
            runCatching { File(track.path).length() }.getOrDefault(0L)
        } else {
            TrackAudioInfoReader.readFileSize(context, track) ?: 0L
        }

    private fun readHead(context: Context, track: MusicTrack): ByteArray {
        val input = openInput(context, track) ?: return ByteArray(0)
        return runCatching { input.use { readFully(it, HEAD_SCAN_BYTES) } }.getOrDefault(ByteArray(0))
    }

    private fun readTail(context: Context, track: MusicTrack): ByteArray? = runCatching {
        val size = fileLength(context, track)
        if (size <= 0) return null
        val start = (size - TAIL_SCAN_BYTES).coerceAtLeast(0)
        val input = openInput(context, track) ?: return null
        input.use { stream ->
            if (!skipFully(stream, start)) return null
            readFully(stream, TAIL_SCAN_BYTES)
        }
    }.getOrNull()

    // 定点读取 [offset, offset + count)：窗口之外的标签块靠它取回；读不满时返回已读部分，
    // 是否可用由调用方按窗口规则判断
    private fun readRange(context: Context, track: MusicTrack, offset: Long, count: Int): ByteArray? = runCatching {
        if (offset < 0 || count <= 0) return null
        val input = openInput(context, track) ?: return null
        input.use { stream ->
            if (!skipFully(stream, offset)) return null
            readFully(stream, count)
        }
    }.getOrNull()

    // InputStream.skip 允许少跳，循环补齐
    private fun skipFully(stream: InputStream, count: Long): Boolean {
        var skipped = 0L
        while (skipped < count) {
            val step = stream.skip(count - skipped)
            if (step <= 0) return false
            skipped += step
        }
        return true
    }

    private fun readFully(stream: InputStream, max: Int): ByteArray {
        val buffer = ByteArray(max)
        var read = 0
        while (read < max) {
            val step = stream.read(buffer, read, max - read)
            if (step <= 0) break
            read += step
        }
        return if (read == max) buffer else buffer.copyOf(read)
    }

    // ID3 文本帧：首字节为编码标志，其余为正文
    private fun id3Text(body: ByteArray): String {
        if (body.size <= 1) return ""
        return decodeId3(body.copyOfRange(1, body.size), body[0].toInt() and 0xFF)
    }

    // COMM/USLT：编码字节 + 3 字节语言 + 简短描述 + \0 + 正文
    private fun commentText(body: ByteArray): String? {
        val payload = splitDescription(body, skip = 4) ?: return null
        return payload.second
    }

    // TXXX/WXXX：编码字节 + 描述 + \0 + 值
    private fun splitDescription(body: ByteArray, skip: Int = 0): Pair<String, String>? {
        if (body.size <= skip + 1) return null
        val encoding = body[0].toInt() and 0xFF
        val payload = body.copyOfRange(1 + skip, body.size)
        val sep = payload.indexOf(0)
        if (sep < 0) return null
        val desc = decodeId3(payload.copyOfRange(0, sep), encoding)
        val value = decodeId3(payload.copyOfRange(sep + 1, payload.size), encoding)
        return desc to value
    }

    // ID3 文本编码：0=latin1，1=utf16(带 BOM)，2=utf16be，3=utf8
    private fun decodeId3(bytes: ByteArray, encoding: Int): String = when (encoding) {
        1 -> String(bytes, Charsets.UTF_16)
        2 -> String(bytes, Charsets.UTF_16BE)
        3 -> String(bytes, Charsets.UTF_8)
        else -> String(bytes, Charsets.ISO_8859_1)
    }

    // 非 ID3 场景的文本（RIFF INFO、MP4 data、W 帧）：截断尾部空字节后按 UTF-8 解码
    private fun plainText(bytes: ByteArray): String {
        var end = bytes.size
        while (end > 0 && (bytes[end - 1].toInt() == 0 || bytes[end - 1].toInt() == 0x20)) end--
        return String(bytes, 0, end, Charsets.UTF_8)
    }

    private fun ByteArray.startsWithAscii(s: String): Boolean =
        size >= s.length && s.indices.all { this[it] == s[it].code.toByte() }

    // MP4 判定：顶层盒子类型为 ftyp/moov/free/mdat/wide 之一
    private fun isMp4Like(bytes: ByteArray): Boolean {
        if (bytes.size < 12) return false
        return when (String(bytes, 4, 4, Charsets.ISO_8859_1)) {
            "ftyp", "moov", "free", "mdat", "wide" -> true
            else -> false
        }
    }

    private fun containsAscii(bytes: ByteArray, needle: String): Boolean =
        indexOf(bytes, needle.toByteArray(Charsets.ISO_8859_1), ignoreCase = true) != null

    private fun indexOf(bytes: ByteArray, needle: ByteArray, ignoreCase: Boolean = false): Int? {
        if (needle.isEmpty() || bytes.size < needle.size) return null
        outer@ for (i in 0..bytes.size - needle.size) {
            for (j in needle.indices) {
                val a = bytes[i + j].toInt() and 0xFF
                val b = needle[j].toInt() and 0xFF
                val equal = if (ignoreCase) lowerAscii(a) == lowerAscii(b) else a == b
                if (!equal) continue@outer
            }
            return i
        }
        return null
    }

    private fun lowerAscii(v: Int): Int = if (v in 65..90) v + 32 else v

    // MP4 条目键的版权前缀在 ISO-8859-1 下是 0xA9，统一规范为 ASCII 的 c
    private fun normalizeMp4Key(name: String): String =
        name.map { if (it.code == 0xA9 || it == '\uFFFD') 'c' else it }.joinToString("")

    // ID3v2 长度字段为 28 位同步安全整数：每字节仅低 7 位有效
    private fun syncSafe(bytes: ByteArray, at: Int): Int =
        if (at + 4 > bytes.size) 0 else
            ((bytes[at].toInt() and 0x7F) shl 21) or
                ((bytes[at + 1].toInt() and 0x7F) shl 14) or
                ((bytes[at + 2].toInt() and 0x7F) shl 7) or
                (bytes[at + 3].toInt() and 0x7F)

    private fun beInt(bytes: ByteArray, at: Int): Int =
        if (at + 4 > bytes.size) 0 else
            ((bytes[at].toInt() and 0xFF) shl 24) or
                ((bytes[at + 1].toInt() and 0xFF) shl 16) or
                ((bytes[at + 2].toInt() and 0xFF) shl 8) or
                (bytes[at + 3].toInt() and 0xFF)

    private fun beInt24(bytes: ByteArray, at: Int): Int =
        if (at + 3 > bytes.size) 0 else
            ((bytes[at].toInt() and 0xFF) shl 16) or
                ((bytes[at + 1].toInt() and 0xFF) shl 8) or
                (bytes[at + 2].toInt() and 0xFF)

    private fun leInt(bytes: ByteArray, at: Int): Int =
        if (at + 4 > bytes.size) 0 else
            (bytes[at].toInt() and 0xFF) or
                ((bytes[at + 1].toInt() and 0xFF) shl 8) or
                ((bytes[at + 2].toInt() and 0xFF) shl 16) or
                ((bytes[at + 3].toInt() and 0xFF) shl 24)
}
